import { neon } from '@neondatabase/serverless';
import nodemailer from 'nodemailer';

const sql = neon(process.env.NETLIFY_DATABASE_URL);

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS
  }
});

export async function handler(event) {
  try {
    const { contact, type } = JSON.parse(event.body);

    if (!contact || (!contact.includes('@') && contact.length < 10)) {
      return { statusCode: 200, body: JSON.stringify({ status: 'fail', message: 'Invalid contact' }) };
    }

    // --- NEW: CHECK IF USER EXISTS BEFORE SENDING OTP ---
    if (type === 'signup') {
        const existingUser = await sql`SELECT * FROM users WHERE email = ${contact}`;
        if (existingUser.length > 0) {
            return { 
                statusCode: 200, 
                body: JSON.stringify({ status: 'exists', message: 'User already exists' }) 
            };
        }
    }
    // ----------------------------------------------------

    const otp = Math.floor(100000 + Math.random() * 900000).toString();

    // Save OTP to DB
    await sql`
      INSERT INTO otps (contact, otp_code) VALUES (${contact}, ${otp})
      ON CONFLICT (contact) DO UPDATE SET otp_code = ${otp}, created_at = NOW()
    `;

    // Email Content Logic
    let emailSubject = "InternetFlox Verification Code";
    const aiFooter = `<br><br><hr><p style="color:gray; font-size:12px;">This mail is generated by AI so don't try to reply.</p>`;
    let emailHtml = `<p>Your Code: <b>${otp}</b></p>${aiFooter}`;

    if (type === 'signup') {
        emailSubject = "Welcome to InternetFlox! 🎬 - Verify Your Account";
        emailHtml = `
            <div style="font-family: Arial; padding: 20px;">
                <h2 style="color: #e50914;">Welcome!</h2>
                <p>Use this code to create your account:</p>
                <h1 style="background: #eee; padding: 10px; display: inline-block;">${otp}</h1>
                ${aiFooter}
            </div>`;
    } else if (type === 'reset') {
        emailSubject = "Security Update 🔒 - Reset Password";
        emailHtml = `
            <div style="font-family: Arial; padding: 20px;">
                <h2 style="color: #333;">Reset Password</h2>
                <p>Use this code to verify your identity:</p>
                <h1 style="color: #e50914;">${otp}</h1>
                ${aiFooter}
            </div>`;
    }

    // Send Email (Only if it's an email address)
    if (contact.includes('@')) {
        await transporter.sendMail({
            from: `"InternetFlox Security" <${process.env.EMAIL_USER}>`,
            to: contact,
            subject: emailSubject,
            html: emailHtml
        });
    }

    return { statusCode: 200, body: JSON.stringify({ status: 'success', message: 'OTP Sent' }) };

  } catch (err) {
    return { statusCode: 500, body: JSON.stringify({ status: 'error', message: err.message }) };
  }
}
