import { neon } from '@neondatabase/serverless';
import nodemailer from 'nodemailer';

const sql = neon(process.env.NETLIFY_DATABASE_URL);

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS
  }
});

export async function handler(event) {
  try {
    // We now extract 'type' (signup or reset) from the request
    const { contact, type } = JSON.parse(event.body);

    if (!contact || !contact.includes('@')) {
      return { statusCode: 200, body: JSON.stringify({ status: 'fail', message: 'Invalid email' }) };
    }

    const otp = Math.floor(100000 + Math.random() * 900000).toString();

    // Save to Database (Logic remains same)
    await sql`
      INSERT INTO otps (contact, otp_code) VALUES (${contact}, ${otp})
      ON CONFLICT (contact) DO UPDATE SET otp_code = ${otp}, created_at = NOW()
    `;

    // --- CUSTOM EMAIL LOGIC ---
    let emailSubject = "";
    let emailHtml = "";

    // Common Footer
    const aiFooter = `<br><br><hr><p style="color:gray; font-size:12px;">This mail is generated by AI so don't try to reply.</p>`;

    if (type === 'signup') {
        // CASE 1: SIGN UP (New Account)
        emailSubject = "Welcome to InternetFlox! 🎬 - Verify Your Account";
        emailHtml = `
            <div style="font-family: Arial, sans-serif; padding: 20px;">
                <h2 style="color: #e50914;">Welcome to InternetFlox!</h2>
                <p>Hi there,</p>
                <p>You are just one step away from unlimited movies and TV shows. Please use the verification code below to complete your account creation.</p>
                <h1 style="background: #eee; padding: 10px; display: inline-block; letter-spacing: 5px; border-radius: 5px;">${otp}</h1>
                <p>If you didn't request this, please ignore this email.</p>
                ${aiFooter}
            </div>
        `;
    } else if (type === 'reset') {
        // CASE 2: RESET PASSWORD (Update)
        emailSubject = "Security Update 🔒 - Reset Your Password";
        emailHtml = `
            <div style="font-family: Arial, sans-serif; padding: 20px;">
                <h2 style="color: #333;">Password Reset Request</h2>
                <p>Hello,</p>
                <p>We received a request to reset the password for your InternetFlox account. Use the OTP below to verify your identity.</p>
                <h1 style="color: #e50914; letter-spacing: 5px;">${otp}</h1>
                <p><strong>Note:</strong> This code will expire shortly. Do not share it with anyone.</p>
                ${aiFooter}
            </div>
        `;
    } else {
        // Default Fallback
        emailSubject = "InternetFlox Verification Code";
        emailHtml = `<p>Your Verification Code is: <b>${otp}</b></p>${aiFooter}`;
    }

    // Send the Email
    await transporter.sendMail({
      from: `"InternetFlox Security" <${process.env.EMAIL_USER}>`,
      to: contact,
      subject: emailSubject,
      html: emailHtml
    });

    return { statusCode: 200, body: JSON.stringify({ status: 'success', message: 'OTP Sent' }) };

  } catch (err) {
    console.error("Error:", err);
    return { statusCode: 500, body: JSON.stringify({ status: 'error', message: err.message }) };
  }
}
